### ISSUE TITLE
Recent update broke deaths 

### ISSUE THREAD

**Issue by JMCY26** [JereKuusela/valheim-wearable_trophies#1]
Hi, since the update of this mod yesterday, the console throws an error on death and my character lays on the floor with no gravestone spawn, screen fades to black and then you cannot do anything until you log out of the world and back in, can you look into this please? When I disable this mod deaths function as normal.

Error on death blocking death/gravestone process: https://pastebin.com/hanJeQ2P

Thanks

**Comment by JereKuusela** [comment]
Thanks for the report. Uploaded a new version with a fix. Sorry for the trouble!

**Comment by JMCY26** [comment]
> Thanks for the report. Uploaded a new version with a fix. Sorry for the trouble!

Amazing, thanks for the help. :)
